### ISSUE TITLE
this lab is expecting tests but there is no spec folder so I cannot complete it

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/basic-nested-forms#22]
![screen shot 2017-09-28 at 8 18 00 am](https://user-images.githubusercontent.com/10333387/30966065-944c57a6-a425-11e7-96b2-c82f2f9a0633.png)

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. This lesson is now a readme.

As always thank you for contributing!
