### ISSUE TITLE
Change in the way the material is presented

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/basic-nested-forms#24]
I noticed since a couple of lessons ago, the way the material is being presented is very different than how the curriculum has been teaching the concepts until now. I feel these last lessons have been a bit scarce, lacking in explanation and elucidation of the concepts. I understand we are now at a more advanced point in the curriculum, but new concepts are still being introduced. As such, I strongly recommend "enriching" these last section of the curriculum, spending just a few more lines explaining new concepts and HOW the methods work. 

Just my humble opinion. Trying to be helpful.

**Comment by drakeltheryuujin** [comment]
Hi @Ary770,
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
