### ISSUE TITLE
Wrong syntax in code along

### ISSUE THREAD

**Issue by grandballoon** [learn-co-curriculum/basic-nested-forms#25]
This lesson instructs you to use "f.fields_for", but the fields only appear when the syntax is entered as "fields_for", without the "f."

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue.

**Comment by JoeQuattrone** [comment]
This is still an issue. The curriculum was not revised!
