### ISSUE TITLE
Wrong example code

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/basic-nested-forms#27]
Hi, I think there is an error in this lab's example code in the "Avoiding Duplicates" section. This is the example provided:
```
class Song < ActiveRecord::Base
  def artist_attributes=(artist)
    self.artist = Artist.find_or_create_by(name: artist.name)
    self.artist.update(artist)
  end
end
```
I noticed is that you are shadowing an instance variable's name `artist` with the local variable `artist` which can be confusing, and I think led to an error in this case. In the line `self.artist = Artist.find_or_create_by(name: artist.name)` self.artist on the left-hand side of the assignment is the instance variable @artist (which is an instance of the Artist class or nil) but the `artist.name` in the argument references the local variable (which will have "preference" in this scope). As such, artist (without a prefix of @ or self-dot) refers to the attribute hash passed in, so artist.name will cause a NoMethodError. To make this code work, I think it needs to be `Artist.find_or_create_by(name: artist[:name])`. You **do** want to reference the local variable here, but the `artist` local variable is a hash object, not an Artist instance, so it has no method `name` - to get the name information of the local variable you need to use `artist[:name]`.

It seems to me like it would be less easy to fall into making the mistake between the two if you renamed the local variable something like `artist_info` or `artist_hash`, and then changed the third line down to 
``` self.artist = Artist.find_or_create_by(name: artist_info[:name])```
or something like that. 

Thanks!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
