### ISSUE TITLE
Bundler error 

### ISSUE THREAD

**Issue by whatstheward** [learn-co-curriculum/basic-nested-forms#29]
I ran into this error while trying to get started on this lab. 

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails
(~> 4.2)', in any of the sources.
```

**Comment by gac2117** [comment]
I removed the version for rails in the Gemfile, so it just states `gem 'rails'` 
I ran `bundle install` and then `bundle update` and it worked for me.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
