### ISSUE TITLE
Passed Local Tests: no tests

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/basic-nested-forms#3]
I built a test for this lab (which was great fun!), but I'm not sure if we are supposed to do that. If so, could add a line to the lab saying, "Please build test(s) to check the validity of this form, using Capybara." Otherwise, there is no way to progress to the next lesson.

**Comment by AnnJohn** [comment]
thanks @onyoo there should be tests, so we'll add them as soon as we can.

**Comment by AnnJohn** [comment]
my bad, there aren't supposed to be tests for this. and we changed it to Learn to be a Readme and not a Lab. Thanks!
