### ISSUE TITLE
Can't use Rails Server or Console 

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/basic-nested-forms#31]
I'm getting this message when I try to view the console and server. 
`/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `raise_in_transactional_callbacks=' for ActiveRecord::Base:Class (NoMethodError)`
Not sure what's going on there.

**Comment by gnappo1** [comment]
Running ```bundle update``` is a good try but should still show the same error.
Try specifying a version for sqlite3, specifically: ```gem 'sqlite3', '~> 1.3.6'```
The issue should be fixed at this point, in case it isn't, try upgrading rails to 5.0: ```gem 'rails', '~> 5.0'```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
