### ISSUE TITLE
Lab won't complete

### ISSUE THREAD

**Issue by jakebrady5** [learn-co-curriculum/basic-nested-forms#5]
Lab will not mark as complete.

When I started the lab, there was a repo to fork, which I did.  Now lab has correctly converted to a readme.  I have two green lights, but lab does not register as complete.

**Comment by AnnJohn** [comment]
hi @jakebrady5 sorry about that. We changed it to a readme since there were no specs for this. You should still fork and clone it but there's nothing to pass.

For the green lights problem, you can use the Ask a Question tool and someone will resolve it there.
