### ISSUE TITLE
Feedback from Students

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/basic-nested-forms#6]
In the Rails Basic Nested Forms reading, is the "Avoiding Duplicates" section saying that when we want to avoid duplicates of the row we're creating, that we don't use accepts_nested_attributes_for ? And in those situations we just create a setter method such in as the example below that with songs and artists?

**people and addresses: you can have multiple people with the same address, so in the Person class, accepts_nested_attributes_for :addresses is ok.

**songs and artists: you can't have duplicates of the artists, because you want to be able to return all of the songs associated with that artist and if the artist is listed more than once, it may not be accurate. So in the Song class, there is no accepts_nested_attributes_for, but instead an artist_attributes= method.

So how come in the Rails Has Many Through in Forms lab, our Post class can still pass the tests with an accepts_nested_attributes_for :categories plus a categories_attributes= method?

**Comment by pletcher** [comment]
I'm not sure I totally understand where this feedback is going.

In the example from the Rails HMTiF Lab, I don't see a `#categories_attributes=` method. But even if there was one, it wouldn't necessarily conflict with `accepts_nested_attributes_for` -- it depends on the implementation of the setter method.

The confusion seems to stem from how that section is worded in this lab.

I think I just answered my own question. Hooray for rubber duck debugging.

![200_s](https://cloud.githubusercontent.com/assets/2015049/13717959/5697b2a0-e7b3-11e5-89a2-92a6f36236eb.gif)
