### ISSUE TITLE
No rspec tests, thus lab cannot be marked as green.

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/basic-nested-forms#9]
There are no rspec tests present, so `learn` never returns complete and the lab cannot be marked as done.

**Comment by SophieDeBenedetto** [comment]
@pletcher is this a lab that is meant to have tests? If so, I'll write them, otherwise I'll just change the designation to "readme" in the curriculum manager

**Comment by pletcher** [comment]
I think we can just toggle it.

**Comment by pletcher** [comment]
Toggled.
